/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Tue May 30 16:51:56 2023.
 */

#include <string.h>

#include "ter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int ter_apps_pack(
    uint8_t *dst_p,
    const struct ter_apps_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->apps_1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->apps_2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->imp_flags, 0u, 0xffu);

    return (8);
}

int ter_apps_unpack(
    struct ter_apps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->apps_1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->apps_2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->imp_flags = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t ter_apps_apps_1_encode(double value)
{
    return (uint8_t)(value);
}

double ter_apps_apps_1_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_apps_apps_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_apps_2_encode(double value)
{
    return (uint8_t)(value);
}

double ter_apps_apps_2_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_apps_apps_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_imp_flags_encode(double value)
{
    return (uint8_t)(value);
}

double ter_apps_imp_flags_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_apps_imp_flags_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ter_pedal_cmd_pack(
    uint8_t *dst_p,
    const struct ter_pedal_cmd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->args, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->args, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->args, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->args, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->args, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->args, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->args, 0u, 0xffu);

    return (8);
}

int ter_pedal_cmd_unpack(
    struct ter_pedal_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->args = unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->args |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t ter_pedal_cmd_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double ter_pedal_cmd_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_pedal_cmd_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t ter_pedal_cmd_args_encode(double value)
{
    return (uint64_t)(value);
}

double ter_pedal_cmd_args_decode(uint64_t value)
{
    return ((double)value);
}

bool ter_pedal_cmd_args_is_in_range(uint64_t value)
{
    return (value <= 1ull);
}

int ter_bpps_pack(
    uint8_t *dst_p,
    const struct ter_bpps_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bpps, 0u, 0xffu);

    return (1);
}

int ter_bpps_unpack(
    struct ter_bpps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bpps = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t ter_bpps_bpps_encode(double value)
{
    return (uint8_t)(value);
}

double ter_bpps_bpps_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_bpps_bpps_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
